import Navbar from '../navbar'
import Footer from '../footer'
import Head from 'next/head'

import styled from 'styled-components';

const ContentContainer = styled.div`
  margin: 4rem 5rem 4rem 8.5rem;
  height: 100%;
  @media (max-width: 40em) {
    margin: 0 3.5rem 4rem 6.5rem;
  }
  @media (max-width: 64em) {
    margin: 0 3.5rem 4rem 6.5rem;
  }
`;

export default function MainLayout({ children, navItems, footerColumns, title }) {
  return (
    <>
      <Head>
        <title>{`${title ? title + ' - ' : ''}Plan A Nijmegen`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#f0250a" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <div>
        <Navbar navItems={navItems} />
        <ContentContainer>
          <main>{children}</main>
          <Footer footerColumns={footerColumns} />
        </ContentContainer>
      </div>
    </>
  )
}