import Navbar from '../navbar'
import Footer from '../footer'
import Head from 'next/head'

import styled from 'styled-components';

const ContentContainer = styled.div`
  margin: 4rem 5rem 4rem 8.5rem;
  height: 100%;
  @media (max-width: 40em) {
    margin: 0 3.5rem 4rem 6.5rem;
  }
  @media (max-width: 64em) {
    margin: 0 3.5rem 4rem 6.5rem;
  }
`;

export default function MainLayout({ children, navItems, footerColumns }) {
  return (
    <>
      <Head>
        <title>Plan A Nijmegen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar navItems={navItems} />
        <ContentContainer>
          <main>{children}</main>
          <Footer footerColumns={footerColumns} />
        </ContentContainer>
      </div>
    </>
  )
}